'use client';
import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';

import { cn } from '../lib/utils';
import Navbar from '@/components/nav/Navbar';
import { usePathname, useRouter } from 'next/navigation';
import Footer from '@/components/nav/Footer';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang='ko' suppressHydrationWarning>
      <body
        className={cn(
          ' bg-background font-sans antialiased',
          fontSans.variable,
          { 'overflow-hidden': pathname === '/trip' }
        )}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
