'use client';
import type { Metadata } from 'next';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';

import { cn } from '../lib/utils';
import Navbar from '@/components/nav/Navbar';
import { usePathname, useRouter } from 'next/navigation';
import Footer from '@/components/nav/Footer';
import ReactQueryProvider from './ReactQueryProvider';
import { Toaster } from '@/components/ui/toaster';
import { useEffect, useState } from 'react';
import Hydration from './hydration';
import useUserIdStore from '@/stores/auth';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
});
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const getIsLogin = useUserIdStore.getState().isLogin;

  useEffect(() => {
    if (pathname == '/trip/') {
      window.scrollTo(0, 0);
    }
  }, [pathname]);

  return (
    <ReactQueryProvider>
      <html lang='ko' suppressHydrationWarning>
        <head>
          <link rel='icon' href='/favicon.ico' sizes='any' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />

          {/* <link
            rel='icon'
            href='/icon?<generated>'
            type='image/<generated>'
            sizes='<generated>'
          />
          <link
            rel='apple-touch-icon'
            href='/apple-icon?<generated>'
            type='image/<generated>'
            sizes='<generated>'
          /> */}
        </head>
        <body
          className={cn(
            pathname != '/trip/'
              ? 'bg-background font-sans antialiased'
              : 'overflow-hidden bg-background font-sans antialiased',
            fontSans.variable
          )}
        >
          <Hydration />
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar getIsLogin={getIsLogin} />

            {children}
            <Toaster />
          </ThemeProvider>
          {pathname != '/trip/' && <Footer />}
        </body>
      </html>
    </ReactQueryProvider>
  );
}
