import type { Metadata } from 'next';
import Footer from '@/app/components/nav/Footer';

import Navbar from '@/app/components/nav/Navbar';
import ScrollToTop from '../components/ScrollToTop';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <ScrollToTop />
      {children}
      {modal}
      <Footer />
    </>
  );
}
